### ISSUE TITLE
Don't block other syncs when one fails

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/temp_app#8]
Currently, if one sync fails, syncs that were enqueued after it cannot be run. I encountered this while testing out the app. If one sync is dependent on the other, we should definitely prevent the dependency from running. But otherwise, you should be able to run one sync even if a prior one failed

**Comment by ryanwjackson** [comment]
The problem here is that there could be bad side effects of not ensuring everything succeeds in order.  Let's take the following example:

A: Update tax rate for customer
B: Create invoice
C: Charge card (not possible but just for the example)

Let's say (A) fails and then you perform (B) and (C).  The result would be incorrect, as it would be using the old tax rate.

At a maximum, I do not think this should be the default behavior, though we could make it a configuration at the app or account level.

The current thought was to use webhooks to alert the provider to the error, give them the tools to update the sync such that it succeeds.  We could also offer the ability to "skip."

**Comment by mattgmarcus** [comment]
Okay that's fair. I think we can get by without this for now. 

Other potentially creative ideas are:
- make syncs behave like a linked list. So you could have a `parent_sync` attribute, and then block based on the order
- since we're passing around references, we could make ledger sync smart enough to know if there's a prior sync operation to an entity that it references. And if that sync is failed/blocked, to not perform. That would require more work but could probably be done I think

**Comment by mattgmarcus** [comment]
I just put the `wontfix` label on this for now, so we won't tackle it yet

**Comment by ryanwjackson** [comment]
@mattgmarcus I think the issue with those ideas is that the app only has so much knowledge of how resources are connected.  But really, that logic lives in the ledger.  In QBO world, `TaxRate` is it's own object.  So knowing that an invoice would use that requires something like `Invoice` -> `LineItem` -> `Product/Service` -> `TaxRate` (and maybe `Customer` is somewhere in there).  I don't think it's reasonable to expect the app to know/maintain that logic/connection.

I guess from my perspective, it's somewhat intractable given that QBO itself makes that logic, and unless it's very clearly documented, we may miss it.

**Comment by mattgmarcus** [comment]
Okay, I think you're right on this. Maybe eventually we can figure something out

**Comment by ryanwjackson** [comment]
Closing for now.

Also notable that cancelling a sync is related in #16
